import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Flow from "@/components/reactflow";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Next + ReactFlow + Tailwind + DaisyUI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="card bg-base-100 h-screen shadow-xl">
          <div className="card-body">
            <h2 className="card-title">React Flow Example</h2>
            <p>Go ahead and play around with it!</p>
            <figure className="h-full">
              <Flow />
            </figure>
          </div>
        </div>
      </main>
    </>
  );
}
